// 자동 생성 파일 - Excel VBA 매크로로 갱신
// Excel 변경 후 '엑셀_데이터_내보내기' 매크로 재실행
const ALL_DATA   = {
  "cur_task":[
    {"id":1,"title":"통합 모델링 고도화","contents":"• 수요예측 모델 정비 및 예측 모델 선택 알고리즘 개발\n  • 제품별, 국가별 수요예측 모델 현황 파악 및 결과 선택 알고리즘 개발\n  • 단계별 validation 지점 도출 및 모니터링 시스템 개발","image":"task/logo_samsung.png","comp_exec":"퀀텀AI","start_month":"2026-04","end_month":"2026-11","comp_mngt":"안진Deloitte","kewards":"제조, 모델선택, 시계열모델, 강화학습, 시각화"},
    {"id":2,"title":"AI 기반 책무 시스템 고도화","contents":"• 책무 업무 프로세스 중 5개 모듈에 대해 AI 기술 적용\n  • Vector, Graph DB 구축 및 프롬프트 설계, 구현\n  • AI Agent 프로세스 설계 및 구현","image":"task/logo_shinhangroup.png","comp_exec":"","start_month":"2026-01","end_month":"2026-07","comp_mngt":"신한DS","kewards":"AI Agent, GraphDB, Prompt Engineering, RAG, VectorDB, 금융, 비즈니스Rule"},
    {"id":3,"title":"제조공정 데이터 분석","contents":"• 분석 모델 고도화\n  • 2025년 개발 모델 고도화 수행","image":"task/logo_stollberg.png","comp_exec":"","start_month":"2026-01","end_month":"2026-06","comp_mngt":"앰버로드","kewards":"제조, 공정데이터, 최적화, 시뮬레이션"}
  ],
  "cmpt_task":[
    {"id":1,"title":"딥러닝 기반 인입콜 예측 알고리즘 개발","contents":"• 시계열 기반 수요 예측 모델 구축\n  • 내,외부 데이터 결합 후 인입콜 건수 예측 알고리즘 개발\n  • AutoML 기반 예측 모델 자동화 설계 및 개발","image":"task/logo_ktCS.png","comp_exec":"","start_month":"2025-10","end_month":"2026-03","comp_mngt":"단독수주","kewards":"시계열모델, 통신"},
    {"id":2,"title":"내부통제 모니터링 자동화 프로세스 컨설팅","contents":"• AI Agent 기반 내부통제 모니터링 자동화 PoC\n  • LLM 기반 내부통제 지표 분석 및 자동화 설계\n  • AI Agent 기반 리스크 탐지 프로세스 설계 및 PoC 수행","image":"task/logo_shinhancard.png","comp_exec":"이엘온소프트","start_month":"2025-10","end_month":"2025-12","comp_mngt":"안진Deloitte","kewards":"PoC, 금융, 비즈니스Rule, 컨설팅"},
    {"id":3,"title":"제조공정 데이터 분석","contents":"• 분석 방향성 수립 및 관리\n  • 이상케이스 특징 분석 및 지표 생성, 제품 코드별 밀도 예측 모델 개발\n  • 투입 자재를 이용한 밀도 시뮬레이션 모델 생성","image":"task/logo_stollberg.png","comp_exec":"","start_month":"2025-07","end_month":"2025-12","comp_mngt":"앰버로드","kewards":"공정데이터, 시뮬레이션, 제조, 최적화"},
    {"id":4,"title":"내부 상시감시 시스템 구축","contents":"• 내부 상시감사 Rule 검증 및 예측 모델 구축\n  • 수신/여신/외환/공통 거래 기반 기존 Rule 적정성 검증\n  • AI 기법을 활용한 신규 Rule 도출 (신규 Rule 추천)\n  • 이상 거래에 대한 원인이 되는 변수 분석 결과 구문을 생성하여 화면에 표시","image":"task/logo_bnk.png","comp_exec":"","start_month":"2024-11","end_month":"2025-05","comp_mngt":"인포디어","kewards":"금융, 분류모델, 불균형데이터, 비즈니스Rule"},
    {"id":5,"title":"이미지기반 성분비 추정모델","contents":"• 탄화 이미지 기반 성분비 추정 모델 개발\n  • 이미지 전처리 및 카테고리 분류 모델 개발\n  • 이미지 탄화 정도에 따른 성분 비율 추정 모델 개발\n  • Deep Learning\n  • Reinforcement Learning","image":"task/logo_kdchem.png","comp_exec":"","start_month":"2024-06","end_month":"2024-12","comp_mngt":"단독수주","kewards":"강화학습, 이미지, 제조"},
    {"id":6,"title":"빅데이터 분석과제 솔루션 개발","contents":"• 빅데이터 분석과제 솔루션 개발 (행안부 주관 2024년 데이터기반행정 실태점검 준비)\n  • 미세먼지 및 가시백연 솔루션 빅데이터 분석모델 개발\n  • 데이터 송신 불가능환경에서 데이터분석으로 태양광 출력 검증 및 예측\n  • 미계량 태양광 발전량 예측모델 개발\n  • 빅데이터 분석 기반 풍속 예측모델 개발","image":"task/logo_ewp.png","comp_exec":"","start_month":"2024-06","end_month":"2024-12","comp_mngt":"단독수주","kewards":"시계열모델, 이미지, 제조, 태양광"},
    {"id":7,"title":"내부 상시감시 시스템 컨설팅","contents":"• 내부 상시감시 Rule 검증 및 예측 모델 생성 방안 제시\n  • 수신/여신/외환/공통 거래 기반 기존 Rule 적정성 검증\n  • 수치기반 모델링 방안 제시","image":"task/logo_jbbank.png","comp_exec":"","start_month":"2024-08","end_month":"2024-10","comp_mngt":"삼정KPMG","kewards":"금융, 비즈니스Rule, 컨설팅"},
    {"id":8,"title":"내부 상시감시 시스템 컨설팅","contents":"• 내부 상시감사 Rule 검증 및 예측 모델 생성 방안 제시\n  • 상시감시 예측 모델링 방안 수립\n  • 내부 거래 데이터 검토 및 시스템 규모 제안","image":"task/logo_bnk.png","comp_exec":"이엘온소프트","start_month":"2024-04","end_month":"2024-05","comp_mngt":"안진Deloitte","kewards":"금융, 비즈니스Rule, 컨설팅"},
    {"id":9,"title":"내부 상시감시 시스템 컨설팅","contents":"• 내부 상시감시 Rule 검증 및 예측 모델 생성 방안 제시\n  • 수신/여신/외환/공통 거래 기반 기존 Rule 적정성 검증\n  • 수치기반 모델링 방안 제시","image":"task/logo_kjbank.png","comp_exec":"","start_month":"2024-03","end_month":"2024-07","comp_mngt":"삼정KPMG","kewards":"금융, 비즈니스Rule, 컨설팅"},
    {"id":10,"title":"기후 환경 분석 시스템 구축","contents":"• 데이터 분석 환경 구축\n  • 분석 환경 아키텍처 설계 및 구축\n  • 분석 과제 교육자료 생성 및 배포\n  • 데이터 분석을 위한 자원관리 및 데이터 관리 시스템 자동화","image":"task/logo_kma.png","comp_exec":"","start_month":"2023-10","end_month":"2024-03","comp_mngt":"이테크시스템","kewards":"공공, 분류모델, 분석인프라, 시계열모델"},
    {"id":11,"title":"자금세탁방지 시스템 고도화","contents":"• 의심거래보고 STR 대상 감지 모델링\n  • 고객 거래내역 분석 및 의심거래 탐지 모델 개발\n  • 재학습 포함 자동화 구현","image":"task/logo_shbank.png","comp_exec":"지티원","start_month":"2023-09","end_month":"2023-12","comp_mngt":"삼정KPMG","kewards":"금융, 분류모델, 자금세탁방지(AML)"},
    {"id":12,"title":"표시제도 온라인 조사 개선 시범사업","contents":"• 5개 은행 상품 설명 데이터 수집 및 적정성 검증\n  • 상품 설명 게시 정보 수집 및 상품 설명 적정성 검증 모델 개발\n  • 언어 모델을 사용한 텍스트 정제 및 변수화, 이미지 적정성 여부 판단 모델 개발","image":"task/logo_kdic.png","comp_exec":"","start_month":"2023-08","end_month":"2023-11","comp_mngt":"단독수주","kewards":"공공, 분류모델, 이미지분류, 크롤링, 텍스트분석"},
    {"id":13,"title":"데이터 분석 매니지먼트 서비스","contents":"• DMP(Data Management Platform) 기반 데이터 분석\n  • 가명 고객 세분화 및 특성 분석\n  • 지표 및 마케팅 가능 대상자 발굴, 실행, 성과 분석","image":"task/logo_nh.png","comp_exec":"","start_month":"2023-01","end_month":"2024-12","comp_mngt":"","kewards":"고객세분화, 과제발굴, 금융, 분류모델, 비식별데이터"},
    {"id":14,"title":"방송 트렌드 및 텍스트 분석","contents":"• 드라마 긍/부정 시청자 반응 분석\n  • 드라마 댓글 수집 및 언어 모델을 활용한 문장 정비, 단어 형태 소 분석 및 비정형 변수 생성\n  • 대시보드 표현을 위한 드라마 반응 분석 결과 도출 및 주요 키워드 도출","image":"task/logo_jtbc.png","comp_exec":"","start_month":"2022-09","end_month":"2023-03","comp_mngt":"대건정보","kewards":"크롤링, 텍스트분석"},
    {"id":15,"title":"기구 신뢰성 검증 플랫폼 개발","contents":"• 제품 개발 단계에 따른 기구 성능 예측 및 최종 시험 통과 확률 예측 플랫폼 개발\n  • 시험 결과 기반 통과 평가 시스템 자동화 및 통과 확률 모델 구현\n  • 알테어 제품을 이용한 데이터 처리 자동화 및 시각화 구현","image":"task/logo_lge.png","comp_exec":"","start_month":"2022-05","end_month":"2022-07","comp_mngt":"한국알테어","kewards":"분류모델, 시각화, 제조"},
    {"id":16,"title":"이상 금융거래 탐지 시스템 구축","contents":"• 이상거래탐지(FDS) 유형 분석 및 모델 개발\n  • 대포 통장 개설 등 이상 거래 Rule 검증 및 판단 모델 개발\n  • 희박한 예측 건에 대해 A.I 모델링 및 구축 지원","image":"task/logo_miraeAssetSC.png","comp_exec":"","start_month":"2020-11","end_month":"2021-04","comp_mngt":"KCB","kewards":"FDS, 금융, 분류모델"},
    {"id":17,"title":"상담결과 분류 체계 구축","contents":"• 연애/상담 결과 텍스트 분류 체계 수립, 모델링 및 자동화\n  • 텍스트 분석 및 고객 성향 분류체계 수립\n  • 고객 성향 분류 모델링 및 운영 프레임워크 개발","image":"task/logo_luvD.png","comp_exec":"","start_month":"2022-03","end_month":"2023-03","comp_mngt":"단독수주","kewards":"MLOps, 분류모델, 텍스트분석"},
    {"id":18,"title":"원자재 선물 가격 예측","contents":"• 팜유, 옥수수, 대두유, 원유, 소맥 등 5종 원자재 선물 가격 예측\n  • 시장국면 예측, 시계열 예측\n  • D+1 원자재 종가\n  • D+5, D+10, M+1, M+2, M+3 원자재 최대/평균/최저 예측\n  • M+6, M+12 상승 확률 예측","image":"task/logo_nongshim.png","comp_exec":"","start_month":"2022-04","end_month":"2022-11","comp_mngt":"단독수주","kewards":"선물지수, 시계열모델, 원자재"},
    {"id":19,"title":"드라마 제작 의사결정 시스템 구축","contents":"• 드라마 제작 평가를 위한 텍스트 감성 분석 및 지수화 (텍스트 분류)\n  • 드라마 반응 댓글 수집 및 문장 단위의 문맥 이해 모델 개발, 단어 대분류 체계 수립\n  • 단어 사전 생성 및 감성지수 생성 모델 구축","image":"task/logo_cjENM.png","comp_exec":"","start_month":"2021-11","end_month":"2022-04","comp_mngt":"단독수주","kewards":"크롤링, 텍스트분석"},
    {"id":20,"title":"마이데이터 서비스 시스템 구축","contents":"• 마이데이터 활용을 위한 분석 서비스 구현 (지수 개발, 상품추천 모델링)\n  • 소비지수 개발, 주 활동 지역 추정 로직 개발, 핫 플레이스 선정 로직 개발\n  • 상품 추천 모델링 및 데이터 분석 기술 이관","image":"task/logo_hanacard.png","comp_exec":"","start_month":"2021-09","end_month":"2022-01","comp_mngt":"삼정KPMG","kewards":"금융, 분류모델, 비즈니스Rule, 지수개발"},
    {"id":21,"title":"이미지 검색 시스템 PoC","contents":"• 이미지 검색을 위한 사전 분류 체계 수립 및 유사 이미지 추천 모델링 (유사 이미지 탐색)\n  • 이미지 카테고리 정의\n  • 이미지 분류 모델링 및 주요 피처 추출 자동화","image":"task/logo_pearlabyss.png","comp_exec":"한국마이크로소프트","start_month":"2021-09","end_month":"2021-12","comp_mngt":"단독수주","kewards":"분류모델, 이미지"},
    {"id":22,"title":"분석 컨설팅","contents":"• 롯데 6개 계열사 분석 과제 수행 (불균형 분류 예측, 시계열 예측, 페르소나 발굴)\n  • 대상 계열사: 마트,슈퍼,하이마트,K7,백화점,캐피탈\n  • 가격 탄력도 분석\n  • 우량 고객(페르소나) 발굴\n  • 빅가전 구매 가능 고객 예측\n  • 점포 세분화\n  • 신규 고객 발굴","image":"task/logo_lotteMembers.png","comp_exec":"","start_month":"2021-08","end_month":"2022-01","comp_mngt":"단독수주","kewards":"분류모델, 비지도학습, 시계열모델, 유통"},
    {"id":23,"title":"이상 금융거래 탐지 시스템 구축","contents":"• 이상거래탐지(FDS) 유형 분석 및 모델 개발\n  • 대포 통장 개설 등 이상 거래 Rule 검증 및 판단 모델 개발\n  • 희박한 예측 건에 대해 A.I 모델링 및 구축 지원","image":"task/logo_samsungSC.png","comp_exec":"","start_month":"2020-11","end_month":"2021-04","comp_mngt":"KCB","kewards":"FDS, 금융, 분류모델"},
    {"id":24,"title":"상품 추천 및 Peer Group 분석","contents":"• 자동화 기계학습 솔루션 기반 상품 추천 모델 개발 및 서베이 기반 Peer Group 분석\n  • 12개 상품군 대상 고객 가입 예측 모델 개발\n  • 서베이 자료 기반 Peer Group 분류를 위한 Factor 산출","image":"task/logo_shinhanbank.png","comp_exec":"","start_month":"2020-08","end_month":"2020-09","comp_mngt":"단독수주","kewards":"AutoML, 금융, 분류모델"},
    {"id":25,"title":"중학교 배정 최적화 컨설팅","contents":"• 중학교 근거리 배정 모델링 및 최적화 (최적화)\n  • 자택 주소 및 인근 중학교 위치 기반 거리 데이터 수집\n  • 거리 기반 최적화 모델링 및 조정 방안 수립, 자동화 구현","image":"task/logo_sen.png","comp_exec":"","start_month":"2020-08","end_month":"2020-11","comp_mngt":"단독수주","kewards":"공공, 선형계획법, 최적화"},
    {"id":26,"title":"빅데이터 플랫폼 구축","contents":"• 자동화 기계학습 솔루션 기반 상품 추천 모델 개발 및 고객등급 고도화 (분류 예측)\n  • 12개 상품군 가입 확률 예측 모델링\n  • 고객 등급 점수화 시뮬레이션 및 분류 방안 수립","image":"task/logo_dgb.png","comp_exec":"CC미디어","start_month":"2019-12","end_month":"2020-05","comp_mngt":"메타넷","kewards":"금융, 분류모델, 비즈니스Rule"},
    {"id":27,"title":"인프라 고도화 사업","contents":"• 주식시장 국면전환, 유사국면, 3~6개월 시장 예측 프로세스 튜닝 (분류/시계열 모델 튜닝)\n  • Python 기반 예측 시스템 프로그램 튜닝 (10시간 이상 단축)\n  • R 기반 시스템 튜닝 가능성 검토 (튜닝 불필요 판단)","image":"task/logo_shinhanAI.png","comp_exec":"굿모닝아이텍","start_month":"2019-09","end_month":"2020-02","comp_mngt":"코오롱베니트","kewards":"금융, 모델실행속도개선, 분류모델, 시계열모델, 파이프라인정비"}
  ],
  "bod":[
    {"id":1,"name":"이 진행","role":"CEO","image":"member/member_ljh.jpg","contents":"  • AI 기반 경영 의사결정 체계 수립 및 전사 전략 방향 설계\n  • 데이터·AI를 활용한 자동화를 통한 비용 절감 방안 제시\n  • 예측 기반 경영관리 체계 도입을 통한 성과 중심 운영 모델 설계\n  • 데이터 중심 조직 전환을 위한 단계별 실행 로드맵 수립","skills":"  • Predictive Analytics 기반 경영성과 최적화 전략 설계 역량\n  • AI·데이터 기반 비즈니스 모델 설계 능력\n  • AutoML 기반 분석 자동화 체계를 통한 생산성 극대화 경험\n  • AI Agent·LLM 활용 의사결정 지원 시스템 기획 및 적용 역량","career":"SAS Korea, 삼성증권, 삼정KPMG, 조인스(주)"},
    {"id":2,"name":"김 효성","role":"CDO","image":"member/member_khs.jpg","contents":"  • 데이터 거버넌스 및 전사 데이터 활용 체계 설계\n  • ML/DL 기반 예측 모델 전략 수립 및 데이터 활용 정책 정의\n  • 데이터 기반 의사결정 문화 정착을 위한 운영 프로세스 설계\n  • 데이터 자산화 및 분석 플랫폼 구축을 위한 아키텍처 전략 수립","skills":"  • 데이터 파이프라인 구축 및 MLOps 기반 운영 체계 설계 역량\n  • AutoML 기반 분석 자동화 및 데이터 활용 효율화 기술\n  • Predictive Analytics 기반 리스크 관리 및 수익 최적화 모델 구현 역량\n  • 대용량 데이터 처리 및 분석 플랫폼 설계·운영","career":"(주) 나이스신용정보"},
    {"id":3,"name":"김 경록","role":"CTO","image":"member/member_kkr.jpg","contents":"  • AI/ML 기반 분석 플랫폼 및 서비스 아키텍처 설계\n  • AI Agent 및 LLM 기반 업무 자동화 시스템 설계 및 기술 전략 수립\n  • 분석 모델의 운영 안정성 확보를 위한 MLOps 체계 설계\n  • 확장성과 성능을 고려한 클라우드·온프레미스 하이브리드 구조 설계","skills":"  • ML/DL 모델 설계 및 고도화 아키텍처 구축 역량\n  • Python 기반 AI 기술 스택(Scikit-learn, TensorFlow, PyTorch) 활용 능력\n  • AI Agent·LLM 기반 서비스 구현 및 시스템 통합 역량\n  • 데이터 처리·모델 서빙·운영 자동화를 포함한 End-to-End 기술 구현 역량","career":"콘텐트리중앙"}
  ],
  "cnsl_partner":[
    {"id":1,"name":"안진 Deloitte","image":"cnsl_partner/logo_deloitte.png","contents":"  • 컴플라이언스 컨설팅 협업\n  • AML, FDS, 상시감시 등 핵심 영역\n  • 단순 자문을 넘어 실증 병행 수행","customer":"경남은행, 신한금융지주, 신한은행, 신한카드"},
    {"id":2,"name":"삼정 KPMG","image":"cnsl_partner/logo_kpmg.png","contents":"  • 컴플라이언스 컨설팅 협업","customer":"광주은행, 수협은행, 전북은행, 하나카드"}
  ],
  "cnstc_partner":[
    {"id":1,"name":"마켓링크","image":"cnstc_partner/logo_marketLink.png","contents":"  • 데이터와 시장을 연결해 성과를 만드는 마케팅 솔루션 기업\n  • 유통 데이터 기반 과제 협업","keyward":"데이터, 마케팅, 시장동향, 유통","url":"https://marketlink.co.kr/"},
    {"id":2,"name":"신한DS","image":"cnstc_partner/logo_shinhanDS.png","contents":"  • 신한금융그룹 대상 사업 협업\n  • AI 기반 사업 협업","keyward":"AI기반사업, 금융, 신한금융그룹","url":"https://www.shinhands.co.kr/"},
    {"id":3,"name":"퀀텀 AI","image":"cnstc_partner/logo_quantumAI.png","contents":"  • 금융권 비정형데이터 자산화 서비스 제공 기업\n  • AI 기반 사업 협업","keyward":"AI기반사업, 금융","url":"https://quantum-ai.ai/index"},
    {"id":4,"name":"이콜트리","image":"cnstc_partner/logo_ecoletree.png","contents":"  • AI 기반 하이퍼오토메이션과 로우코드 기술 전문 기업\n  • 제조 사업 협업","keyward":"AI기반사업, 제조","url":"http://ecoletree.com/"},
    {"id":5,"name":"토라웨어","image":"cnstc_partner/logo_torahWare.png","contents":"  • 금융/제조 시스템 구축 전문 기업\n  • 시스템 구현 부분 협업","keyward":"금융, 제조","url":"https://www.torahware.com/kor/main/index.php"},
    {"id":6,"name":"스카이앤드","image":"cnstc_partner/logo_skyand.png","contents":"  • 금융 시스템 구축 전문 기업\n  • 신한퓨처스랩 동문 기업\n  • 시스템 구현 부분 협업","keyward":"AI기반사업, 금융, 신한금융그룹","url":"https://skyand.co.kr/"},
    {"id":7,"name":"앰버로드","image":"cnstc_partner/logo_amberRoad.png","contents":"  • 제조 공정 생산성 향상을 위한 맞춤형 솔루션 제공 기업\n  • 제조 산업 협업","keyward":"AI기반사업, 제조","url":"https://amberroad.ai/"},
    {"id":8,"name":"탈피오트 컨설팅","image":"cnstc_partner/logo_talpiot.png","contents":"  • 기업의 성장전략, 인증 및 전문역량 확보 지원 전문 기업\n  • 정부 사업 협업","keyward":"AI기반사업, 공공사업","url":"https://talpiot.co.kr/"}
  ]
};
const COLOR_MAPS = {
  "task_keyward":{"금융":"brown","비즈니스Rule":"blue","분류모델":"red","이상탐지":"gray","시계열모델":"orange","모델실행속도개선":"pink","파이프라인정비":"gray","공공":"green","최적화":"purple","선형계획법":"yellow","AutoML":"yellow","FDS":"blue","유통":"gray","시계열예측":"purple","비지도학습":"green","이미지":"blue","지수개발":"orange","텍스트분석":"green","크롤링":"purple","선물지수":"blue","원자재":"orange","MLOps":"yellow","제조":"green","시각화":"brown","과제발굴":"gray","비식별데이터":"orange","고객세분화":"brown","이미지분류":"gray","자금세탁방지(AML)":"purple","분석인프라":"pink","컨설팅":"green","불균형데이터":"green","강화학습":"pink","태양광":"red","공정데이터":"orange","시뮬레이션":"brown","PoC":"gray","통신":"pink","AI Agent":"blue","RAG":"blue","VectorDB":"pink","GraphDB":"pink","Prompt Engineering":"pink"},
  "comp_mngt":{"단독수주":"pink","코오롱베니트":"red","KCB":"purple","메타넷":"orange","삼정KPMG":"gray","한국알테어":"yellow","대건정보":"brown","이테크시스템":"green","안진Deloitte":"gray","인포디어":"blue","엠버로드":"gray","신한DS":"yellow"},
  "cmmp_exec":{"굿모닝아이텍":"gray","CC미디어":"yellow","한국마이크로소프트":"purple","지티원":"red","인포디어":"brown","안진Deloitte":"orange","이엘온소프트":"blue","퀀텀AI":"pink","없음":"default"},
  "role":{"CEO":"blue","CTO":"green","CDO":"yellow","COO":"brown","Design":"pink","Engineering":"gray"},
  "career":{"콘텐트리중앙":"orange","(주) 나이스신용정보":"blue","SAS Korea":"red","삼정KPMG":"gray","삼성증권":"yellow","조인스㈜":"brown"},
  "cnsl_customer":{"Agriculture":"orange","Energy":"purple","Healthcare":"blue","Security":"brown","Education":"yellow","Food delivery":"green","Finance":"pink","신한은행":"gray","신한금융지주":"gray","신한카드":"red","경남은행":"gray","하나카드":"red","광주은행":"purple","전북은행":"brown","수협은행":"orange"},
  "cnst_keyward":{"유통":"gray","데이터":"pink","마케팅":"gray","시장동향":"red","금융":"green","신한금융그룹":"pink","AI기반사업":"red","제조":"red","공공사업":"blue"}
};
